services:
  mongodb:
    image: mongo:7.0
    container_name: franchise-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: franchisedb
    volumes:
      - mongo-data:/data/db
    networks:
      - franchise-network

  app:
    build: .
    container_name: franchise-app
    ports:
      - "8080:8080"
    environment:
      MONGODB_URI: mongodb://mongodb:27017/franchisedb
    depends_on:
      - mongodb
    networks:
      - franchise-network

volumes:
  mongo-data:

networks:
  franchise-network:
    driver: bridge
